/*
 * Copyright (c) 1994-2014 Stephane Poirier
 *
 * stephane.poirier@oifii.org
 *
 * Stephane Poirier
 * 3532 rue Ste-Famille, #3
 * Montreal, QC, H2X 2L1
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by oifii_app.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_GOTOPARTITION               101
#define IDP_SOCKETS_INIT_FAILED         102
#define IDR_MAINFRAME_OLD               103
#define IDR_MAINFRAME_STATUS_BAR        104
#define IDR_OW2MDIFRAME_STATUS_BAR      105
#define IDR_COMMON                      106
#define IDR_COMMON_GE                   107
#define IDR_COMMON_OL                   108
#define IDC_ZOOMIN                      109
#define IDR_ZOOM                        110
#define IDR_MAINFRAME1                  111
#define IDD_VIEW                        112
#define IDD_VIEWDATASETTINGS            113
#define IDD_FUSION                      114
#define IDD_FUSIONSETTINGS              115
#define IDD_HISTO                       116
#define IDD_HISTOSETTINGS               117
#define IDD_SCATTER                     118
#define IDD_SCATTERSETTINGS             119
#define IDD_EXTRACTION                  120
#define IDD_EXTRACTIONSETTINGS          121
#define IDC_ZOOMRECTDRAG                122
#define IDD_PROJECTIONSETTINGS          123
#define IDD_TRANSFORMATIONSETTINGS      124
#define IDC_ZOOMRECT                    125
#define IDR_COMMON_AG                   126
#define IDP_OLE_INIT_FAILED             130
#define IDR_MAINFRAME                   131
#define IDC_ZOOMOUT                     132
#define IDR_OW2VIEW_POPUP               133
#define IDD_CLASSIFICATIONSETTINGS      134
#define IDR_COMMON1                     135
#define IDR_COMMON_GE1                  136
#define IDC_ROIRECT                     137
#define IDD_TRACESETTINGS               138
#define IDC_ROIRECTDRAG                 139
#define IDD_BEHAVIORSETTINGS            140
#define IDC_ROIPOLYLINE                 141
#define IDD_PROFILESETTINGS             142
#define IDC_ROIPOLYLINEDRAG             143
#define IDC_ROIFREEHAND                 144
#define IDC_ROIFREEHANDDRAG             145
#define IDS_OPEN_FILTEREXTENSIONS       192
#define IDS_OPEN_ALL_SUPPORTED          193
#define IDS_OPEN_TIFF                   194
#define IDS_OPEN_BITMAP                 195
#define IDS_OPEN_MIM                    196
#define IDS_OPEN_MOD                    197
#define IDS_OPEN_RAW                    198
#define IDS_OPEN_PCX                    199
#define IDS_OPEN_TARGA                  200
#define IDS_OPEN_GIF                    201
#define IDS_OPEN_JPEG                   202
#define IDS_OPEN_BST                    203
#define IDS_OPEN_SCR                    204
#define IDS_OPEN_ALL_FILES              205
#define IDS_OPEN_END                    206
#define IDS_SAVE_MONO_FILTEREXTENSIONS  208
#define IDS_SAVE_MONO_TIFF_UNCOMPRESSED 209
#define IDS_SAVE_MONO_TIFF_LZW          210
#define IDS_SAVE_MONO_BMP_UNCOMPRESSED  211
#define IDS_SAVE_MONO_BMP_COMPRESSED    212
#define IDS_SAVE_MONO_RAW               213
#define IDS_SAVE_MONO_JPEG              214
#define IDS_SAVE_MONO_PCX_UNCOMPRESSED  215
#define IDS_SAVE_MONO_GIF               216
#define IDS_SAVE_MONO_TARGA             217
#define IDS_SAVE_MONO_END               218
#define IDS_SAVE_COLOR_FILTEREXTENSIONS 224
#define IDS_SAVE_COLOR_TIFF_UNCOMPRESSED 225
#define IDS_SAVE_COLOR_TIFF_LZW         226
#define IDS_SAVE_COLOR_BMP_UNCOMPRESSED 227
#define IDS_SAVE_COLOR_JPEG             228
#define IDS_SAVE_COLOR_PCX_UNCOMPRESSED 229
#define IDS_SAVE_COLOR_TARGA            230
#define IDS_SAVE_COLOR_END              231
#define IDS_FILE_TYPE_TIFF_UNCOMPRESSED 275
#define IDS_FILE_TYPE_BMP_UNCOMPRESSED  276
#define IDS_FILE_TYPE_PCX_UNCOMPRESSED  277
#define IDS_FILE_TYPE_TARGA             278
#define IDS_FILE_TYPE_GIF               279
#define IDS_FILE_TYPE_WPG               280
#define IDS_FILE_TYPE_WMF               281
#define IDS_FILE_TYPE_TIFF_HUFFMAN      282
#define IDS_FILE_TYPE_TIFF_G3_FAX       283
#define IDS_FILE_TYPE_TIFF_LZW          284
#define IDS_FILE_TYPE_TIFF_G4_FAX       285
#define IDS_FILE_TYPE_DCX               286
#define IDS_FILE_TYPE_BMP_COMPRESSED    287
#define IDS_FILE_TYPE_JPEG              288
#define IDS_FILE_TYPE_EPS               289
#define IDS_FILE_TYPE_PICT              290
#define IDS_FILE_TYPE_TIFF_PACK         291
#define IDS_FILE_TYPE_TIFF_G3_2D        292
#define IDS_FILE_TYPE_MIM               293
#define IDS_FILE_TYPE_MOD_              294
#define IDS_FILE_TYPE_RAW_              295
#define IDS_FILE_TYPE_BLOB_             296
#define IDS_FILE_TYPE_ERROR             297
#define ID_VIEW_ZOOM_BASE               300
#define ID_VIEW_ZOOM_IN_11              301
#define ID_VIEW_ZOOM_IN_21              302
#define ID_VIEW_ZOOM_IN_31              303
#define ID_VIEW_ZOOM_IN_41              304
#define ID_VIEW_ZOOM_IN_51              305
#define ID_VIEW_ZOOM_IN_61              306
#define ID_VIEW_ZOOM_IN_71              307
#define ID_VIEW_ZOOM_IN_81              308
#define ID_VIEW_ZOOM_OUT_11             317
#define ID_VIEW_ZOOM_OUT_12             318
#define ID_VIEW_ZOOM_OUT_13             319
#define ID_VIEW_ZOOM_OUT_14             320
#define ID_VIEW_ZOOM_OUT_15             321
#define ID_VIEW_ZOOM_OUT_16             322
#define ID_VIEW_ZOOM_OUT_17             323
#define ID_VIEW_ZOOM_OUT_18             324
#define ID_VIEW_TOFIT                   332
#define ID_VIEW_ZOOM                    333
#define ID_BASE_POPUP_GRAPHMENU0        350
#define ID_BASE_POPUP_GRAPHMENU1        351
#define ID_BASE_POPUP_GRAPHMENU2        352
#define ID_BASE_POPUP_GRAPHMENU3        353
#define ID_BASE_POPUP_GRAPHMENU4        354
#define ID_BASE_POPUP_GRAPHMENU5        355
#define ID_BASE_POPUP_GRAPHMENU6        356
#define ID_BASE_POPUP_GRAPHMENU7        357
#define ID_BASE_POPUP_GRAPHMENU8        358
#define ID_BASE_POPUP_GRAPHMENU9        359
#define ID_BASE_POPUP_GRAPHMENU10       360
#define ID_BASE_POPUP_GRAPHMENU11       361
#define ID_BASE_POPUP_GRAPHMENU12       362
#define ID_BASE_POPUP_GRAPHMENU13       363
#define ID_BASE_POPUP_GRAPHMENU14       364
#define ID_BASE_POPUP_GRAPHMENU15       365
#define ID_BASE_POPUP_GRAPHMENU16       366
#define ID_BASE_POPUP_GRAPHMENU17       367
#define ID_BASE_POPUP_GRAPHMENU18       368
#define ID_BASE_POPUP_GRAPHMENU19       369
#define ID_BASE_POPUP_GRAPHMENU20       370
#define ID_VIEW_SELECTION_BAR           402
#define ID_VIEW_COMPOSITE               403
#define ID_VIEW_COMP3                   404
#define ID_VIEW_COMP4                   405
#define ID_VIEW_COMPMDI                 406
#define ID_VIEW_IMAGE_INFO              407
#define ID_VIEW_AS_LINEGRAPH            408
#define ID_VIEW_AS_VBARGRAPH            409
#define ID_VIEW_AS_HBARGRAPH            410
#define ID_VIEW_FIT_ALL                 411
#define ID_VIEW_FIT_ONEVALUEPERPIXEL    412
#define ID_VIEW_GRAPH                   413
#define ID_VIEW_GRAPHDATA               414
#define ID_OPTIONS_AUTORESCALING        415
#define ID_VIEW_GLOBALHISTOGRAM         500
#define ID_VIEW_LOCALHISTOGRAM          501
#define ID_VIEW_NEW2DVIEW               502
#define ID_VIEW_NEW3DVIEW               503
#define ID_VIEW_NEWGRAPHVIEW            504
#define ID_VIEW_GRAPHDATAVIEW           505
#define ID_VIEW_NEWSELECTIONZOOMVIEW    506
#define ID_VIEW_GOTOPARTITION           507
#define ID_VIEW_GOTOCLASSIFICATION      508
#define ID_VIEW_PIXELSET                509
#define ID_VIEW_POINTSET                510
#define ID_VIEW_TRIANGLESET             511
#define ID_VIEW_VORONOISET              512
#define ID_VIEW_SEGMENTSET              513
#define ID_VIEW_PIXELSET_INTENSITY      514
#define ID_VIEW_PIXELSET_HUE            515
#define ID_VIEW_PIXELSET_SATURATION     516
#define ID_VIEW_PIXELSET_RED            517
#define ID_VIEW_PIXELSET_GREEN          518
#define ID_VIEW_PIXELSET_BLUE           519
#define ID_VIEW_POINTSET_MARK           520
#define ID_VIEW_POINTSET_CROSS          521
#define ID_VIEW_POINTSET_ELLIPSE        522
#define ID_VIEW_POINTSET_LABELS         523
#define ID_VIEW_TRIANGLESET_LABELS      524
#define ID_VIEW_TRIANGLESET_CENTERPOINTS 525
#define ID_VIEW_TRIANGLESET_3VERTICES   526
#define ID_VIEW_TRIANGLESET_POLYGON     527
#define ID_VIEW_VORONOISET_LABELS       528
#define ID_INDICATOR_ZERO               641
#define ID_INDICATOR_ONE                642
#define ID_INDICATOR_TWO                643
#define ID_INDICATOR_THREE              644
#define ID_INDICATOR_FOUR               645
#define ID_OW2MDIFRAME_INDCR_ZERO       657
#define ID_OW2MDIFRAME_INDCR_ONE        658
#define ID_OW2MDIFRAME_INDCR_TWO        659
#define ID_OW2MDIFRAME_INDCR_THREE      660
#define ID_OW2MDIFRAME_INDCR_FOUR       661
#define IDR_HTML1                       701
#define IDR_HTML2                       702
#define IDGOTONEXT                      996
#define IDC_STATIC2                     997
#define IDC_STATIC1                     998
#define IDC_STATIC3                     999
#define IDPLAY                          1000
#define IDSTOP                          1001
#define IDGOTO                          1002
#define IDC_STATIC4                     1003
#define IDC_PIXELSETEDIT                1004
#define IDC_STATIC5                     1005
#define IDC_PIXELSETSTATIC              1006
#define IDC_STATIC6                     1007
#define IDC_POINTSETEDIT                1008
#define IDC_POINTSETSTATIC              1009
#define IDC_TRIANGLESETEDIT             1010
#define IDC_TRIANGLESETSTATIC           1011
#define IDC_VORONOISETEDIT              1012
#define IDC_VORONOISETSTATIC            1013
#define IDC_SEGMENTSETEDIT              1014
#define IDC_SEGMENTSETSTATIC            1015
#define IDC_VIEWCHANNELEDIT             1016
#define IDC_VIEWCHANNELCOMBO            1017
#define IDC_FUSIONCHANNELCOMBO          1018
#define IDC_POINTSETLABELSSTATIC        1018
#define IDC_SCATTERCHANNELCOMBO         1019
#define IDC_PRECLASSIFICATIONCHANNELCOMBO 1020
#define IDC_TRIANGLESETLABELSSTATIC     1021
#define IDC_SCATTERCHANNELCOMBO1        1022
#define IDC_LOCALSTATCHANNELCOMBO       1023
#define IDC_SEGMENTSETLABELSSTATIC      1024
#define IDC_SCATTERCHANNELCOMBO2        1025
#define IDC_NEIGHBORHOODEDIT            1026
#define IDC_TRIANGLESETCENTERSSTATIC    1027
#define IDC_THRESHOLDEDIT               1028
#define IDC_VVSRIGHTEDIT                1029
#define IDC_GIVENSEGMENTEDIT            1030
#define IDC_CLASSSETLABELS              1031
#define IDC_SCALEEDIT                   1032
#define IDC_VVSTOPEDIT                  1033
#define IDC_MTIGNORECHECK               1034
#define IDC_VVSBOTTOMEDIT               1035
#define IDC_MTUSEITCHECK                1036
#define IDC_VVSNEAREDIT                 1037
#define IDC_MTTRANSLATEZEDIT            1038
#define IDC_VVSFAREDIT                  1039
#define IDC_MTTRANSLATEYEDIT            1040
#define IDC_VVSPERSPECTIVECHECK         1041
#define IDC_MTTRANSLATEXEDIT            1042
#define IDC_VVSORTHOGRAPHICCHECK        1043
#define IDC_MTSCALEXEDIT                1044
#define IDC_LAEYEXEDIT                  1045
#define IDC_MTSCALEYEDIT                1046
#define IDC_LAEYEYEDIT                  1047
#define IDC_MTSCALEZEDIT                1048
#define IDC_LACENTERXEDIT               1049
#define IDC_MTROTATEXEDIT               1050
#define IDC_LACENTERYEDIT               1051
#define IDC_MTROTATEYEDIT               1052
#define IDC_LAEYEZEDIT                  1053
#define IDC_MTROTATEZEDIT               1054
#define IDC_LACENTERZEDIT               1055
#define IDC_BUTTON1                     1056
#define IDC_LAIGNORECHECK               1057
#define IDC_TCDDETECTCHECK              1058
#define IDC_VTWIDTHEDIT                 1059
#define IDC_LAUSEITCHECK                1060
#define IDC_TCCAREACHECK                1061
#define IDC_VTHEIGHTEDIT                1062
#define IDC_VVSLEFTEDIT                 1063
#define IDC_TCCDENSITYCHECK             1064
#define IDC_MTABSOLUTECHECK             1065
#define IDC_TCCHEIGHTCHECK              1066
#define IDC_MTRELATIVECHECK             1067
#define IDC_TCCAVERAGEINTENSITYCHECK    1068
#define IDC_LAUPXEDIT                   1069
#define IDC_TCCSPECTRALVARIABILITYCHECK 1070
#define IDC_VTYEDIT                     1071
#define IDC_LAUPYEDIT                   1072
#define IDC_VTXEDIT                     1073
#define IDC_LAUPZEDIT                   1074
#define IDC_STHSOCHECK                  1075
#define IDC_STHRGCHECK                  1076
#define IDC_STMIXEDHSOHRGCHECK          1077
#define IDC_STATISTICMINEDIT            1078
#define IDC_STATISTICMAXEDIT            1079
#define IDC_CSCWEXCLUSIONTHRESHOLDCHECK 1080
#define IDC_CSCWEXCLUSIONTHRESHOLDEDIT  1081
#define IDC_EXCLUDEROADCHECK            1082
#define IDC_CSCWPRECLASSIFICATIONCHECK  1083
#define IDC_EXCLUDEMANMADECHECK         1084
#define IDC_EXCLUDEFORESTCHECK          1085
#define IDC_EXCLUDEDEFORESTATIONCHECK   1086
#define IDC_TRAINING                    1087
#define IDC_CTSUPERVISEDCHECK           1088
#define IDC_CTNONSUPERVISEDCHECK        1089
#define IDC_TLASTAT1CHECK               1090
#define IDC_HISTOCHECK                  1091
#define IDC_TLASTAT1COMBO               1092
#define IDC_SCATTERCHECK                1093
#define IDC_TLASTAT2COMBO               1094
#define IDC_TLASTAT2CHECK               1095
#define IDC_TLASTAT3COMBO               1096
#define IDC_TLASTAT3CHECK               1097
#define IDC_MBLOCALEXTRACTIONCHECK      1098
#define IDC_MBLOCALSEGMENTATIONCHECK    1099
#define IDC_TLASTAT4COMBO               1100
#define IDC_MBHIGHLIGHTNEARESTPOINTCHECK 1101
#define IDC_TLASTAT4CHECK               1102
#define IDC_MBHIGHLIGHTSEGMENTCHECK     1103
#define IDC_MBLOCALCLASSIFICATIONCHECK  1104
#define IDC_IBSELFTRAININGCHECK         1105
#define IDC_IBSELFEXTRACSEGMENTVALIDCHECK 1106
#define IDC_CANCELBUTTON                1107
#define IDC_OKBUTTON                    1108
#define IDC_APPLYBUTTON                 1109
#define IDC_HISTOFRAMESTATIC            1110
#define IDC_MBHIGHLIGHTNEARESTNEIGHBORSCHECK 1111
#define IDC_GIVENSEGMENTCHECK           1112
#define IDC_LOCALNEIGHBORHOODCHECK      1113
#define IDC_GLOBALCHECK                 1114
#define IDC_IMAGEHISTOCHECK             1115
#define IDC_LOCALROICHECK               1115
#define IDC_STATHISTOCHECK              1116
#define IDC_DEFAULTSCOMBO               1117
#define IDC_LOCALROICHECK2              1117
#define IDC_PROFILEFRAMESTATIC          1118
#define IDC_IMAGEPIXELSCHECK            1119
#define IDC_IMAGEFEATURESCHECK          1120
#define IDC_COMBOSTATIC                 1121
#define IDC_SCALE_AUTO                  1122
#define IDC_SCALE_FIT                   1123
#define IDC_TRAININGBUTTON              1124
#define IDC_COMBOSTATIC2                1124
#define IDC_CLASSNAMELISTBOX            1125
#define IDC_DELETEBUTTON                1126
#define IDC_ADDBUTTON                   1127
#define IDC_CLASSNAMEEDIT               1128
#define IDC_DRAWELLIPSE                 1129
#define IDC_DRAWELLIPSEDRAG             1130
#define ID_INITIAL_EDIT                 2005
#define ID_FINAL_EDIT                   2006
#define ID_TODISPLAY_EDIT               2007
#define ID_TOSTART_EDIT                 2008
#define ID_TOEND_EDIT                   2009
#define IDC_LOCALPOINTCOLLECTIONCOMBO   2010
#define ID_ZOOMP_50                     22774
#define ID_ZOOMP_100                    22775
#define ID_ZOOMP_150                    22776
#define ID_ZOOMP_10                     22777
#define ID_ZOOM_ZOOMTOFIT               22780
#define ID_ZOOM_ZOOMNORMAL              22781
#define ID_ZOOMP_75                     22783
#define ID_ZOOMP_200                    22784
#define ID_ZOOMP_400                    22785
#define ID_ZOOMP_800                    22786
#define ID_ZOOM_ZOOMOFF                 22787
#define ID_TEST_POINTSET                32771
#define ID_TEST_SEGMENTSET              32772
#define ID_TEST_TREEFINDER              32773
#define ID_OPTIONS_POINTSETTRACE        32774
#define ID_OPTIONS_SEGMENTSETTRACE      32775
#define ID_OPTIONS_PIXELSETTRACE        32776
#define ID_TEST_PIXELSET                32777
#define ID_TEST_EDGESET                 32780
#define ID_BEHAVIOR_TRACE_PIXELSET      32786
#define ID_BEHAVIOR_TRACE_POINTSET      32787
#define ID_BEHAVIOR_TRACE_SEGMENTSET    32788
#define ID_BEHAVIOR_TRACE_TRIANGLESET   32789
#define ID_BEHAVIOR_TRACE_VORONOISET    32790
#define ID_ANALYSIS_TEXTUREEXTRACTION   32791
#define ID_ANALYSIS_TEXTURESEGMENTATION 32792
#define ID_SETTINGS_EXTRACTION          32796
#define ID_SETTINGS_HISTO               32797
#define ID_SETTINGS_SCATTER             32798
#define ID_SETTINGS_FUSION              32799
#define ID_SETTINGS_VIEWDATA            32800
#define ID_SETTINGS_PROJECTION          32801
#define ID_SETTINGS_TRANSFORMATION      32802
#define ID_ANALYSIS_LOCALEXTRACTION     32803
#define ID_ANALYSIS_LOCALSEGMENTATION   32804
#define ID_ANALYSIS_GLOBALCLASSIFICATION 32805
#define ID_ANALYSIS_LOCALCLASSIFICATION 32806
#define ID_SETTINGS_CLASSIFICATION      32807
#define ID_SETTINGS_TRACEBEHAVIOR       32808
#define ID_SETTINGS_PROFILE             32811
#define ID_TRANS_SPATIAL_STRETCH        32816
#define ID_TRANS_SPATIAL_ROTATION       32817
#define ID_TRANS_SPECTRAL_INVERT        32818
#define ID_TRANS_TEMPORAL_EVOLVE        32824
#define ID_TRANSFORMATION_LAUNCHSEQUENCE 32826
#define ID_ANALYSIS_LAUNCHSCENARIO      32827
#define ID_TRANS_LAUNCHSCENARIO         32828
#define ID_TRANSFORMATION_REPEATINSEQUENCE 32830
#define ID_TRANS_SPATIAL_CONFINEDSTRETCH 32831
#define ID_TRANS_SPECTRAL_HSI           32839
#define ID_TRANS_SPATIAL_EDGEDETECT     32840
#define ID_TRANS_SPATIAL_FLATDETECT     32841
#define ID_TRANS_SPATIAL_MAXDETECT      32842
#define ID_TRANS_SPECTRAL_STRETCH       32843
#define ID_TRANS_SPECTRAL_EQUALIZE      32844
#define ID_TRANS_SPATIAL_SHARPEN        32845
#define ID_FILE_ACQUIRE                 32846
#define ID_ANALYSIS_SCALE_SELECTION     32851
#define ID_TRANS_SPECTRAL_FILTER        32852
#define ID_ROI_RECT                     32854
#define ID_ROI_POLYLINE                 32855
#define ID_ROI_FLOATING                 32856
#define ID_ROI_FREEHAND                 32857
#define ID_ZOOMP_1000                   32864
#define ID_ZOOMP_1500                   32865
#define ID_ZOOMP_2000                   32866
#define ID_ZOOMP_2500                   32867
#define ID_ZOOMP_3000                   32868
#define ID_VIEW_SEGMENTSET_LABELS       32869
#define ID_VIEW_CLASSSET_LABELS         32870
#define ID_VIEW_LOGWINDOW               32872
#define ID_TRANS_SPECTRAL_CONVERTTOMONO 32873
#define ID_TRANS_SPECTRAL_CONVERTTOMONO_SET 32874
#define ID_TRANSPORT_                   32875
#define ID_TRANSPORT_PLAY               32876
#define ID_TRANSPORT_STOP               32877
#define ID_TRANSPORT_PAUSE              32878
#define ID_ZOOM_PERCENT                 57609
#define ID_ZOOM_IN                      57610
#define ID_ZOOM_OUT                     57611
#define ID_ZOOM_POINTIN                 57612
#define ID_ZOOM_POINTOUT                57613
#define ID_ZOOM_RECTIN                  57614
#define ID_INDICATOR_LOCATION           59142
#define ID_INDICATOR_ZOOMP              59394
#define ID_INDICATOR_ZOOMF              59395
#define ID_INDICATOR_POINT              59396
#define IDW_COMBO                       60000
#define ID_SETTINGS_IDLEBEHAVIOR        65535
#define ID_SETTINGS_MOUSEBEHAVIOR       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        703
#define _APS_NEXT_COMMAND_VALUE         32879
#define _APS_NEXT_CONTROL_VALUE         2011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
